version: '3'

volumes:
  bundle:
  node_modules:
  db:

services:
  db:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dbpass

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    tmpfs: /app/tmp
    depends_on:
      - db
    env_file: app.env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"

  smtp:
    image: 'djfarrelly/maildev:latest'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'
