---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - ["default", 2]

:max_retries: 15

:scheduler:
  :schedule:
    clean_category_image:
      cron: "0 0 * * *"
      class: CategoryImageJob
